
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const faqs = [
  {
    question: "How does the Fishing Success Score work?",
    answer: "Our score is generated by a proprietary algorithm that analyzes dozens of data points, including weather, pressure trends, cloud cover, time of day, and moon phase, all weighed against species-specific behavior models for fish like bass, bream, and carp."
  },
  {
    question: "Is my location data kept private?",
    answer: "Yes. Your location data is only used to fetch forecasts for your selected spots and is never shared or sold. Your saved spots are private to your account."
  },
  {
    question: "Which weather provider do you use?",
    answer: "We use the highly-regarded Open-Meteo API, which provides global, high-resolution weather forecasts without requiring an API key for its free tier. This allows us to provide a powerful service at a low cost."
  },
  {
    question: "Can I use the app offline?",
    answer: "Absolutely. When you save a favorite spot, AquaCast automatically caches the latest forecast and map tiles for that area, so you can access critical information even when you're far from a cell tower."
  },
   {
    question: "Which fish species do you support?",
    answer: "Currently, our detailed behavior models are tuned for Bream, Bass, and Carp. We are constantly working to add more species based on user feedback."
  },
];


export function Faq() {
  return (
    <section id="faq" className="py-12 md:py-20 bg-background">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-headline font-bold text-ink-900">Frequently Asked Questions</h2>
        </div>
        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
                 <AccordionItem key={index} value={`item-${index}`}>
                    <AccordionTrigger className="text-lg font-semibold text-left">{faq.question}</AccordionTrigger>
                    <AccordionContent className="text-base text-ink-500">
                        {faq.answer}
                    </AccordionContent>
                </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
}
